### ISSUE TITLE
ToastNotification style different from style partal

### ISSUE THREAD

**Issue by ashleyyang0610** [trendmicro-frontend/react-notifications#2]
http://style-portal.tw.trendnet.org/#/styles/minimalism/latest/168263ea-0f3f-4782-8a37-f18334007680

In style portal, there should be shadow and border-radius style in ToastNotification. 
`box-shadow: 1px 1px 4px rgba(0, 0, 0, 0.2);`
`border-radius: 3px;`

**Comment by cheton** [comment]
Fixed in v1.0.0 (2048564db08dd60bd57f34d5191e1a03544494b0)
